# Generated by Django 5.1.1 on 2024-09-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_name', models.CharField(max_length=200)),
                ('season', models.PositiveIntegerField()),
                ('episode_number', models.PositiveIntegerField()),
                ('release_time', models.TimeField()),
                ('release_date', models.DateField()),
                ('release_day', models.CharField(max_length=10)),
            ],
        ),
    ]
