# Generated by Django 5.1.1 on 2024-09-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
