# Generated by Django 5.1.1 on 2024-09-27 21:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB_api', '0002_alter_anime_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
