# Generated by Django 5.1.1 on 2024-09-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB_api', '0003_anime_created_datetime_anime_updated_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='SbApiAnimeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.CharField(max_length=50)),
                ('anime_name', models.CharField(max_length=200)),
                ('season', models.PositiveIntegerField()),
                ('episode_number', models.PositiveIntegerField()),
                ('release_time', models.TimeField()),
                ('release_date', models.DateField()),
                ('release_day', models.CharField(max_length=10)),
                ('function_type', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sb_api_anime_audit_log',
            },
        ),
    ]
