# Generated by Django 5.1.1 on 2024-09-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB_api', '0004_sbapianimeauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbapianimeauditlog',
            name='created_datetime',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='sbapianimeauditlog',
            name='updated_datetime',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
