# Generated by Django 5.1.1 on 2024-09-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB_api', '0005_sbapianimeauditlog_created_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbapianimeauditlog',
            name='timestamp',
            field=models.DateTimeField(default=None),
        ),
    ]
