# Generated by Django 5.1.1 on 2024-09-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SB_api', '0006_alter_sbapianimeauditlog_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbapianimeauditlog',
            name='timestamp',
        ),
    ]
