# Generated by Django 5.1.1 on 2024-09-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB_api', '0007_remove_sbapianimeauditlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbapianimeauditlog',
            name='created_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sbapianimeauditlog',
            name='updated_datetime',
            field=models.DateTimeField(),
        ),
    ]
